### ISSUE TITLE
just testing

### ISSUE THREAD

**Issue by ritgig** [LawleyFall2017/110-fall2017#1]
So the images of directory structure in the exercise don't match. media should be a subdirectory of igme110.  Cheers  
Did it get attached to the correct file?

**Comment by mamamusings** [comment]
Fixed. Also fixed the broken reference to the second page image, and made some other minor edits, all listed in the commit history.

**Comment by mamamusings** [comment]
Alas, issues don't seem to get attached to specific files the way pull requests do. :(
