### ISSUE TITLE
Readings for week 07 - incorrect link?

### ISSUE THREAD

**Issue by ritgig** [LawleyFall2017/110-fall2017#7]
the link for CSS layout horizontal and vertical align (after inline block) links to inline block:
should be:
https://www.w3schools.com/css/css_align.asp

**Comment by mamamusings** [comment]
I don’t see anything about CSS layout in the week 7 readings. 

It would be great if you could make this edit and submit a pull request—much quicker and easier than me trying to find the specific instance in a document :)
